targetInstance: ${TEST_URL:http://localhost:8093}

s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
s2s-name: rd_judicial_ref_api
idam.api.url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
oauth2.client.secret: ${CA_REF_OAUTH2_CLIENT_SECRET:??}
idam.auth.clientId: ${CA_REF_OAUTH2_CLIENT_ID:rd-judicial-ref-api}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-caseworker-ref-api-aat.service.core-compute-aat.internal/oauth2redirect}
s2s-secret: ${S2S_SECRET:}

jrd.security.roles.hmcts-admin: jrd-admin
jrd.security.roles.system-user: jrd-system-user
