server:
  port: ${PORT:8093}

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

testing:
  support:
    enabled: ${TEST_IDAM_ENABLED:false}
    idamUrl: ${TEST_IDAM_URL:}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        default_schema: dbjuddata
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: Judicial Data API
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:https://idam-web-public.aat.platform.hmcts.net/o}
        registration:
          oidc:
            client-id: ${IDAM_CLIENT_ID:microservicekey-rd-judicial-api}
            client-secret: ${JUDICIAL_API_S2S_SECRET:}
  cache:
    cache-names: token
    caffeine:
      spec: maximumSize=50,expireAfterWrite=1m
  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: true
    locations: ${JUDICIAL_DB:classpath:db/migration}
    schemas:
      - dbjuddata

### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}?currentSchema=dbjuddata
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    min-idle: 1
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

  config:
    import: "optional:configtree:/mnt/secrets/rd/"

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/readiness"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
    - "/refdata/internal/elink/**"

### dependency configuration
idam:
  s2s-auth:
    totp_secret: ${JUDICIAL_API_S2S_SECRET:}
    microservice: rd_judicial_api
    url: ${S2S_URL:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}
  s2s-authorised:
    services: ${JRD_S2S_AUTHORISED_SERVICES:rd_judicial_api,am_org_role_mapping_service,iac,xui_webapp}
  api.url: ${idam_url:https://idam-api.aat.platform.hmcts.net}

oidc.issuer: ${OIDC_ISSUER_URL:https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts}
loggingComponentName: RD-Judicial-Ref-Api
feign:
  allow:
    headers:
      - authorization
  client:
    config:
      default:
        loggerLevel: full

defaultPageSize: ${DEFAULTPAGESIZE:10}

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:preview}
    user: rd

locationRefDataUrl: ${LOCATION_REF_DATA_URL:http://rd-location-ref-api-aat.service.core-compute-aat.internal}
refresh:
  pageSize: ${REFRESH_PAGE_SIZE:200}
  sortColumn: ${REFRESH_SORT_COLUMN:objectId}

search:
  serviceCode: ${JRD_SEARCH_SERVICE_CODE:bfa1,bba3,aaa6,aaa7,aba5,aba3}

elinksApiKey: ${judicial_api_elinks_api_key:}
elinksUrl: ${ELINKS_URL:https://jo-staging.elinks.judiciary.uk/api/v4}

logging.level.uk.gov.hmcts.reform: DEBUG

elastic:
  search:
    query: ${JRD_SIDAM_SEARCH_QUERY:(roles:judiciary) AND lastModified:>now-%sh}
    recordsPerPage: 500
