server:
  port: 8093

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

spring:
  flyway.locations: classpath:db/testmigration
  flyway.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 10
          time_zone: UTC
  main:
    allow-bean-definition-overriding: true
  application:
    name: RD Judicial Ref API
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbjuddata
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    min-idle: 1
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://0.0.0.0:6000/o}
        registration:
          oidc:
            client-id: ${IDAM_CLIENT_ID:microservicekey-rd-judicial-api}
            client-secret: ${JUDICIAL_API_S2S_SECRET:}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/readiness"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"

idam:
  s2s-auth:
    totp_secret: ${JUDICIAL_API_S2S_SECRET:}
    microservice: rd_judicial_api
    url: ${S2S_URL:http://127.0.0.1:8990}
  s2s-authorised:
    services: rd_judicial_api
  api.url: ${IDAM_URL:http://127.0.0.1:5000}

## IDAM feign connection
auth.idam.client.baseUrl: ${http://127.0.0.1:5000/o}
oidc:
  issuer: ${OIDC_ISSUER:http://127.0.0.1:5000/openam/oauth2/hmcts}
  expiration: 14400000 # milliseconds 4 hours

feign:
  allow:
    headers:
      - authorization
      - serviceauthorization

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8990}

# resent user invite interval in minutes
resendInterval: 60

# sync time interval in minutes
syncInterval: 60

defaultPageSize: ${DEFAULTPAGESIZE:10}

loggingComponentName: RD-Judicial-API
