server:
  port: 8093

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

spring:
  flyway.locations: classpath:db/testmigration
  flyway.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 10
          time_zone: UTC
  main:
    allow-bean-definition-overriding: true
  application:
    name: RD Judicial Ref API
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: ${DB_URL:jdbc:tc:postgresql:11.1:///dbjuddata}
    username: ${DB_USERNAME:dbjuddata}
    password: ${DB_PASSWORD:dbjuddata}
    min-idle: 1
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://0.0.0.0:6000/o}
        registration:
          oidc:
            client-id: ${IDAM_CLIENT_ID:microservicekey-rd-judicial-api}
            client-secret: ${JUDICIAL_API_S2S_SECRET:}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/readiness"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-ui/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/v3/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"
    - "/swagger-ui/**"
    - "/v3/**"
    - "/status/health"
    - "/actuator/**"
    - "/refdata/internal/elink/**"
idam:
  s2s-auth:
    totp_secret: ${JUDICIAL_API_S2S_SECRET:}
    microservice: rd_judicial_api
    url: ${S2S_URL:http://127.0.0.1:8990}
  s2s-authorised:
    services: rd_judicial_api
  api:
    url: ${IDAM_URL:http://127.0.0.1:5000}
    client-id: ${OAUTH2_CLIENT_ID:rd-professional-api}
    redirect-uri: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
    authorization: ${OAUTH2_AUTH:}
    client-authorization: ${OAUTH2_CLIENT_AUTH:}

## IDAM feign connection
auth.idam.client.baseUrl: ${http://127.0.0.1:5000/o}
oidc:
  issuer: ${OIDC_ISSUER:http://127.0.0.1:5000/openam/oauth2/hmcts}
  expiration: 14400000 # milliseconds 4 hours

feign:
  allow:
    headers:
      - authorization
      - serviceauthorization

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8990}

# resent user invite interval in minutes
resendInterval: 60

# sync time interval in minutes
syncInterval: 60

defaultPageSize: ${DEFAULTPAGESIZE:10}

loggingComponentName: RD-Judicial-API

locationRefDataUrl: ${LOCATION_REF_DATA_URL:http://rd-location-ref-api-aat.service.core-compute-aat.internal}
search:
  serviceCode: ${JRD_SEARCH_SERVICE_CODE:bfa1,bba3,aaa6,aaa7,aba5,aba3}
refresh:
  pageSize: ${REFRESH_PAGE_SIZE:200}
  sortColumn: ${REFRESH_SORT_COLUMN:objectId}
testing:
  support:
    idamUrl: ${http://127.0.0.1:5000/o}


elinksApiKey: ${judicial_api_elinks_api_key:}
#URL not tested , code is for developers reference
elinksUrl: ${ELINKS_URL:http://127.0.0.1:8000}

elinks:
  people:
    lastUpdated: 2015-01-01
    perPage: 50
    page: 1
    includePreviousAppointments : false
    threadPauseTime: 2000
    threadRetriggerPauseTime: 1000
  scheduler:
    wrapperApiUrl: ${ELINKS_WRAPPER_API_URL:http://localhost:8093}
    cronExpression: ${CRON_EXPRESSION:* * */5 * * *}
    enabled: false


elastic:
  search:
    query: (roles:judiciary) AND lastModified:>now-12h
    recordsPerPage: 500

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:preview}
    user: rd
jrd:
  publisher:
    azure:
      service:
        bus:
          host: ${JRD_MQ_HOST:rd-servicebus-sandbox.servicebus.windows.net}
          username: ${JRD_MQ_USERNAME:SendAndListenSharedAccessKey}
          # JUST TEMPORARY VALUES FOR LOWER ENVIRONMENT
          password: ${JUDICIAL_TOPIC_PRIMARY_SEND_LISTEN_SHARED_ACCESS_KEY:TEST}
          topic: ${JRD_MQ_TOPIC_NAME:rd-judicial-topic-sandbox}
          # DO NOT SET THIS 'true' IN PRODUCTION!
          trustAllCerts: ${JRD_MQ_TRUST_ALL_CERTS:false}
    jrd-message-batch-size: ${JRD_DATA_PER_MESSAGE:50}
  security:
    roles:
      hmcts-admin: jrd-admin
      system-user: jrd-system-user

sendgrid:
  key: ${SENDGRID_API_KEY:}
  mail:
    from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}

email:
  mailTypes:
    asb:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "%s :: Publishing of JRD messages to ASB failed"
      body: "Publishing of JRD messages to ASB failed for Job Id %s"
    report:
      enabled: false
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "%s :: JRD - Execution Failed"
      body: "Execution Failed for files - %s"
    userprofile:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "Official Sensitive: JRD - Incorrect JO Profile Configurations - %s"
      body: "Following JO profiles were deleted : \n %s"
      template: simple-template-userProfile.ftl
    lowerLevelAuth:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "Official Sensitive: JRD - New Lower Level in Authorisations - %s"
      template: lower-level-auth.ftl