spring:
  flyway.locations: classpath:db/testmigration

  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbjuddata
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://0.0.0.0:6000/o}
        registration:
          oidc:
            client-id: microservicekey-rd-judicial-api
            client-secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/readiness"
    - "/health/liveness"
    - "/actuator/**"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/csrf"
    - "/error"
    - "/favicon.ico"

idam:
  s2s-authorised:
    services: ${JRD_S2S_AUTHORISED_SERVICES:rd_judicial_api}
  s2s-auth:
    totp_secret: ${S2S_SECRET:}
    microservice: rd_judicial_api
    url: ${S2S_URL:http://127.0.0.1:8990}
  api.url: ${IDAM_URL:http://127.0.0.1:5000}
  client:
    redirect_uri: https://rd-judicial-api-aat.service.core-compute-aat.internal/oauth2redirect
    id: rd-judicial-api

## IDAM feign connection
auth.idam.client.baseUrl: ${http://127.0.0.1:5000/o}
oidc:
  issuer: ${OIDC_ISSUER:http://127.0.0.1:5000/openam/oauth2/hmcts}
  expiration: 14400000 # milliseconds 4 hours

feign:
  allow:
    headers:
      - authorization
      - serviceauthorization

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:8990}

# resent user invite interval in minutes
resendInterval: 60

# sync time interval in minutes
syncInterval: 60

defaultPageSize: ${DEFAULTPAGESIZE:10}

loggingComponentName: RD_Judicial_API
