spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dbjuddata
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}

security:

  authorisedServices:
    - "it"
## IDAM feign connection
auth.idam.client.baseUrl: ${IDAM_URL:http://127.0.0.1:5000}

exui.role:
  caseworker: caseworker
  pui-organisation-manager: pui-organisation-manager