DELETE FROM judicial_service_code_mapping;

ALTER TABLE judicial_service_code_mapping
ADD COLUMN service_id VARCHAR(16) NOT NULL,
ADD COLUMN ticket_code VARCHAR(16) NOT NULL;

INSERT INTO judicial_service_code_mapping (service_id,jurisdiction,lower_level,ticket_code,service_code,service_description)
VALUES ('1','Authorisation Tribunals','00 - Interlocutory','368','BBA3,,'Social Security and Child Support''),
('2','Authorisation Tribunals','01 - Social Security','364','BBA3,,'Social Security and Child Support''),
('3','Authorisation Tribunals','02 - Child Support','362','BBA3,,'Social Security and Child Support''),
('4','Authorisation Tribunals','03 - Disability Living Allowance','365','BBA3,,'Social Security and Child Support''),
('5','Authorisation Tribunals','04 - Incapacity Benefit Employment Support','366','BBA3,,'Social Security and Child Support''),
('6','Authorisation Tribunals','05 - Industrial Injuries','367','BBA3,,'Social Security and Child Support''),
('7','Authorisation Tribunals','07 - Vaccine Damage','369','BBA3,,'Social Security and Child Support''),
('8','Authorisation Civil','Administrative Court','290',' ,,'''),
('9','Authorisation Civil','Admiralty - QBD','291',' ,,'''),
('10','Authorisation Magistrate','Adult Court','387',' ,,'''),
('11','Authorisation Tribunals','Agricultural Land and Drainage','318','BGA1,,'Agricultural Land and Drainage''),
('12','Authorisation Family','Ancillary Relief Appeals','402','ABA2,,'Financial Remedy''),
('13','Authorisation Crime','Appeals in Crown Court','303',' ,,'''),
('14','Authorisation Tribunals','Asylum Support','320',' ,,'''),
('15','Authorisation Crime','Attempted Murder','304',' ,,'''),
('16','Authorisation Tribunals','Care Standards','321','BCA1,,'Care Standards''),
('17','Authorisation Crime','Central Criminal Court','305',' ,,'''),
('18','Authorisation Civil','Chancery','292',' ,,'''),
('19','Authorisation Civil','Chancery Business in the County Court','293',' ,,'''),
('20','Authorisation Tribunals','Charity','322','BAA2,,'Charity''),
('21','Authorisation Tribunals','Child Support 02','363','BBA3,,'Social Security and Child Support''),
('22','Authorisation Civil','Circuit Commercial Court','407',' ,,'''),
('23','Authorisation Civil','Civil Authorisation','294','AAA1,,'Civil Enforcement''),
('23','Authorisation Civil','Civil Authorisation','294','AAA2,,'Insolvency''),
('23','Authorisation Civil','Civil Authorisation','294','AAA3,,'Mortgage and Landlord Possession Claims''),
('23','Authorisation Civil','Civil Authorisation','294','AAA4,,'Non-money Claims''),
('23','Authorisation Civil','Civil Authorisation','294','AAA5,,'Return of Goods Claims''),
('23','Authorisation Civil','Civil Authorisation','294','AAA6,,'Specified Money Claims''),
('23','Authorisation Civil','Civil Authorisation','294','AAA7,,'Damages''),
('24','Authorisation Civil','Commercial','295',' ,,'''),
('25','Authorisation Tribunals','Competition Appeal Tribunal','325',' ,,'''),
('26','Authorisation Tribunals','Consumer Credit','326','BAA4,,'Consumer Credit''),
('27','Authorisation Crime','Court of Appeal Criminal Division','307',' ,,'''),
('28','Authorisation Family','Court of Protection','313','ABA7,,'Court of Protections''),
('29','Authorisation Crime','Criminal Authorisation','306',' ,,'''),
('30','Authorisation Tribunals','Criminal Injuries Compensations','328','BBA2,,'Criminal Injuries Compensation''),
('31','Authorisation Magistrate','Direct Recruitment to Family','405','ABA3,,'Family Public Law''),
('31','Authorisation Magistrate','Direct Recruitment to Family','405','ABA4,,'Adoption''),
('31','Authorisation Magistrate','Direct Recruitment to Family','405','ABA5,,'Family Private Law''),
('31','Authorisation Magistrate','Direct Recruitment to Family','405','ABA8,,'REMO''),
('32','Authorisation Tribunals','Environment','331','BAA5,,'Environment''),
('33','Authorisation Tribunals','Estate Agents','332','BAA6,,'Estate Agents''),
('34','Authorisation Crime','Extradition','308',' ,,'''),
('35','Authorisation Magistrate','Family Court','389','ABA3,,'Family Public Law''),
('35','Authorisation Magistrate','Family Court','389','ABA4,,'Adoption''),
('35','Authorisation Magistrate','Family Court','389','ABA5,,'Family Private Law''),
('35','Authorisation Magistrate','Family Court','389','ABA8,,'REMO''),
('36','Authorisation Family','Financial Remedy','410','ABA2,,'Financial Remedy''),
('37','Authorisation Civil','Financial Remedy ','409',' ,,'''),
('38','Authorisation Family','Financial Remedy Appeals','314','ABA2,,'Financial Remedy''),
('39','Authorisation Tribunals','First Tier - General Regulatory','392',' ,,'''),
('40','Authorisation Tribunals','First Tier - Health, Education and Social Care','374',' ,,'''),
('41','Authorisation Tribunals','First Tier - Immigration and Asylum','373','BFA1,,'Immigration and Asylum Appeals''),
('42','Authorisation Tribunals','First Tier - Property','375',' ,,'''),
('43','Authorisation Tribunals','First Tier - Social Entitlement','376','BBA3,,'Social Security and Child Support''),
('44','Authorisation Tribunals','First Tier - Tax','377',' ,,'''),
('45','Authorisation Tribunals','First Tier - War Pensions and Armed Forces Compensation','378','BEA1,,'War Pensions Appeals''),
('46','Authorisation Civil','Freezing Orders in the County Court','395',' ,,'''),
('47','Authorisation Tribunals','Gambling','334','BAA8,,'Gambling Appeals''),
('48','Authorisation Tribunals','Information Rights','336','BAB1,,'Information Rights''),
('49','Authorisation Tribunals','Judicial Review - England and Wales','337',' ,,'''),
('50','Authorisation Tribunals','Land Registration','340','BGA2,,'Land Registration''),
('51','Authorisation Tribunals','Local Government Standards - England','341','BAB2,,'Local Government Standards''),
('52','Authorisation Civil','London Circuit Commercial Court','406',' ,,'''),
('53','Authorisation Civil','Media and Communications List','412',' ,,'''),
('54','Authorisation Tribunals','Mental Health','342','BCA2,,'Mental Health''),
('55','Authorisation Tribunals','Mental Health Tribunal Wales','343','BCA2,,'Mental Health''),
('56','Authorisation Civil','Mercantile - QBD','298',' ,,'''),
('57','Authorisation Crime','Murder','309',' ,,'''),
('58','Authorisation Tribunals','National Security','346',' ,,'''),
('59','Authorisation Civil','Ordinary Planning','404',' ,,'''),
('60','Authorisation Tribunals','Others - Employment Appeals Tribunal','379','BHA1,,'Employment Claims''),
('61','Authorisation Tribunals','Others - Gender Recognition Panel','381',' ,,'''),
('62','Authorisation Tribunals','Others - Pathogens Access Appeals Commission','382',' ,,'''),
('63','Authorisation Tribunals','Others - Proscribed Organisations Appeal Commission','383',' ,,'''),
('64','Authorisation Tribunals','Others - Special Immigration Appeals Commission','384','BBA1,,'Asylum Support''),
('65','Authorisation Civil','Patents','299',' ,,'''),
('66','Authorisation Tribunals','Pensions Regulations','347',' ,,'''),
('67','Authorisation Tribunals','Police Appeal Tribunal','350',' ,,'''),
('68','Authorisation Crime','Pool of Judges','394',' ,,'''),
('69','Authorisation Tribunals','Primary Health List','349','BCA3,,'Primary Health Lists''),
('70','Authorisation Family','Private Law','315','ABA5,,'Family Private Law''),
('71','Authorisation Family','Public Law','316','ABA3,,'Family Public Law''),
('72','Authorisation Tribunals','Race Panel','351',' ,,'''),
('73','Authorisation Tribunals','Reinstatement Committee','352',' ,,'''),
('74','Authorisation Tribunals','Reserve Forces','353','BHA3,,'Reserve Forces Appeal Tribunal''),
('75','Authorisation Tribunals','Residential Property','354','BGA3,,'Residential Property''),
('76','Authorisation Tribunals','Restricted Patients Panel','356',' ,,'''),
('77','Authorisation Civil','S9(4) Appointment - Chancery','397',' ,,'''),
('78','Authorisation Family','S9(4) Appointment - Family','400',' ,,'''),
('79','Authorisation Civil','S9(4) Appointment - Queens Bench','398',' ,,'''),
('80','Authorisation Family','Section 9-1 Family','317',' ,,'''),
('81','Authorisation Civil','Section 9(1) Chancery','300',' ,,'''),
('82','Authorisation Civil','Section 9(1) IPEC','396',' ,,'''),
('83','Authorisation Civil','Section 9(1) Queens Bench','301',' ,,'''),
('84','Authorisation Civil','Section 9(1) Queens Bench - Admin ONLY','393',' ,,'''),
('85','Authorisation Crime','Serious Sexual Offences','311',' ,,'''),
('86','Authorisation Crime','Serious Sexual Offences - Youth Court','312',' ,,'''),
('87','Authorisation Civil','Significant Planning','408',' ,,'''),
('88','Authorisation Tribunals','Social Security and Child Support','357','BBA3,,'Social Security and Child Support''),
('89','Authorisation Tribunals','Special Educational Needs and Disability','358',' ,,'''),
('90','Authorisation Civil','Super Planning','411',' ,,'''),
('91','Authorisation Civil','Technology and Construction Court','302',' ,,'''),
('92','Authorisation Crime','Terrorism','310',' ,,'''),
('93','Authorisation Tribunals','Trade Marks Tribunal','359',' ,,'''),
('94','Authorisation Tribunals','Transport','360','BAB3,,'Transport''),
('95','Unknown','Unknown','370',' ,,'''),
('96','Authorisation Tribunals','Upper - Administrative Appeals','371',' ,,'''),
('97','Authorisation Tribunals','Upper - Immigration and Asylum','372','BAA9,,'Immigration Services''),
('98','Authorisation Tribunals','Upper - Lands','385',' ,,'''),
('99','Authorisation Tribunals','Upper - Tax and Chancery','386','BDA2,,'Tax Appeals''),
('100','Languages','Welsh','289',' ,,'''),
('101','Authorisation Magistrate','Youth Court','388',' ,,''');