apiVersion: v2
appVersion: "0.1"
description: Reference data service for judiciary
name: rd-judicial-api
version: 0.0.21
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: 4.0.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
