java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    JUDICIAL_DB: classpath:db/migration
    JRD_MQ_HOST: "$(JRD_MQ_HOST).servicebus.windows.net"
    JUDICIAL_TOPIC_PRIMARY_SEND_LISTEN_SHARED_ACCESS_KEY: "$(JRD_MQ_PASSWORD)"
    JRD_MQ_TOPIC_NAME: jrdapi-aks-topic
    JRD_MQ_USERNAME: SendAndListenSharedAccessKey
    JRD_MQ_TRUST_ALL_CERTS: false
    JRD_DATA_PER_MESSAGE: 50
    LAUNCH_DARKLY_ENV: "preview"
    ENVIRONMENT_NAME: "preview"
    JRD_SEARCH_SERVICE_CODE: bfa1,bba3
  postgresql:
    enabled: true
    auth:
      username: dbjuddata
      password: dbjuddata
      database: dbjuddata
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: judicial-api-s2s-secret
          alias: JUDICIAL_API_S2S_SECRET
        - name: judicial-api-elinks-api-key
          alias: judicial_api_elinks_api_key
        - name: judicial-topic-primary-connection-string
          alias: JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING
        - name: OAUTH2-CLIENT-SECRET
          alias: OAUTH2_CLIENT_SECRET
        - name: OAUTH2-AUTH
          alias: OAUTH2_AUTH
        - name: OAUTH2-CLIENT-AUTH
          alias: OAUTH2_CLIENT_AUTH
        - name: rd-sendgrid-api-key
          alias: RD_SENDGRID_API_KEY
  secrets:
    JRD_MQ_PASSWORD:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: primaryKey
    JRD_MQ_HOST:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: namespaceName
servicebus:
  enabled: true
  teamName: RD
  resourceGroup: rd-aks
  serviceplan: standard
  setup:
    topics:
      - name: jrdapi-aks-topic
        subscriptionNeeded: yes
