java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    JUDICIAL_DB: classpath:db/migration,classpath:db/migrationAks
    LAUNCH_DARKLY_ENV: "preview"
    ENVIRONMENT_NAME: "preview"
  postgresql:
    enabled: true
    postgresqlUsername: dbjuddata
    postgresqlPassword: dbjuddata
    postgresqlDatabase: dbjuddata
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: judicial-api-s2s-secret
          alias: JUDICIAL_API_S2S_SECRET