java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    JUDICIAL_DB: classpath:db/migration
    LAUNCH_DARKLY_ENV: "preview"
    ENVIRONMENT_NAME: "preview"
    JRD_SEARCH_SERVICE_CODE: bfa1,bba3
  postgresql:
    enabled: true
    auth:
      username: dbjuddata
      password: dbjuddata
      database: dbjuddata
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: judicial-api-s2s-secret
          alias: JUDICIAL_API_S2S_SECRET
        - name: judicial-api-elinks-api-key
          alias: judicial_api_elinks_api_key
        - name: judicial-topic-primary-connection-string
          alias: JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING
        - name: OAUTH2-CLIENT-SECRET
          alias: OAUTH2_CLIENT_SECRET
        - name: OAUTH2-AUTH
          alias: OAUTH2_AUTH
        - name: OAUTH2-CLIENT-AUTH
          alias: OAUTH2_CLIENT_AUTH
        - name: rd-sendgrid-api-key
          alias: RD_SENDGRID_API_KEY
